on:
  push:
    branches:
      - master

name: Deploy vscode extension

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run compile
      - uses: lannonbr/vsce-action@master
        with:
          args: 'publish -p $VSCE_TOKEN'
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
